info:
  description: A plugin that allows the user to get data from GitHub using ChatGPT. If you do not know the user's username, ask them first before making queries to the plugin. Otherwise, use the username "global".
  title: GitHub Plugin
  version: v1
openapi: 3.0.1
paths:
  /graphql:
    post:
      operationId: graphql
      summary: Execute a GraphQL query on GitHub
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The GraphQL query string.
                variables:
                  type: object
                  description: The variables for the GraphQL query.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: The JSON response from the GitHub GraphQL API.
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://github.com/login/oauth/authorize
          tokenUrl: https://github.com/login/oauth/access_token
          scopes: {}
security:
  - OAuth2: []
